### ISSUE TITLE
Azure DevOps Issue

### ISSUE THREAD

**Issue by BillChirico** [seraphx2/ado-discord-webhook#1]
When adding a service hook to Azure DevOps there is no selection for Discord. I selected Slack and pasted my webhook URL, but it is failing to send.

**Comment by seraphx2** [comment]
Of course slack won't work. It's for discord. Can you send a screenshot with the task open so I can see what you are trying to do?

**Comment by seraphx2** [comment]
it's a build/release task listed under utility.

**Comment by BillChirico** [comment]
I was looking at the wrong spot. Thank you!

**Comment by qdot** [comment]
I was just having this problem too, luckily the beta issue reporter brought up this bug before I filed a duplicate. Might be worth adding this info to the README.
