### ISSUE TITLE
Support for service hooks

### ISSUE THREAD

**Issue by RudeySH** [seraphx2/ado-discord-webhook#7]
In Azure DevOps, service hooks can be configured to send HTTP post requests on various events: Code pushed, Pull request created, Release deployment completed, etc.

Unfortunately, the request body format is not compatible with Discord Webhooks. To solve this, there needs to be a middle man that converts incoming messages from Azure DevOps to a format that Discord expects.

Is this something ado-discord-webhook can solve?

**Comment by seraphx2** [comment]
Honestly I don't know off hand. I am no task creator guru...lol.
I'd have to do a lot of research to understand and make something like that.
I'll leave this open and maybe look into it in the near future.
